# Configuration de la connexion à la base de données

In [1]:
import pandas as pd 
import cx_Oracle
import sys
import os

%pylab inline
%load_ext sql

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

In [2]:
sys.path.append(os.path.abspath('../../.'))
from dbconnect import utilisateur,connexion,password

# Connexion

In [3]:
%sql oracle+cx_oracle://$utilisateur:$password@$connexion

<img src="https://raw.githubusercontent.com/rbizoi/IntelligenceEnDonneesDeSante/main/InterrogationSQL/images/612.png" width="800">

# L’opérateur UNION

<img src="https://raw.githubusercontent.com/rbizoi/IntelligenceEnDonneesDeSante/main/InterrogationSQL/images/union.png" width="400">

In [4]:
%%sql 
SELECT SOCIETE,VILLE,'Client' FROM CLIENTS 
UNION 
SELECT SOCIETE,VILLE,'Fournisseur' FROM FOURNISSEURS

 * oracle+cx_oracle://stagiaire:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Alfreds Futterkiste', 'Berlin', 'Client'),
 ('Ana Trujillo Emparedados y helados', 'México D.F.', 'Client'),
 ('Antonio Moreno Taquería', 'México D.F.', 'Client'),
 ('Around the Horn', 'London', 'Client'),
 ('Aux joyeux ecclésiastiques', 'Paris', 'Fournisseur'),
 ("B's Beverages", 'London', 'Client'),
 ('Berglunds snabbköp', 'Luleå', 'Client'),
 ('Bigfoot Breweries', 'Bend', 'Fournisseur'),
 ('Blauer See Delikatessen', 'Mannheim', 'Client'),
 ('Blondel père et fils', 'Strasbourg', 'Client'),
 ("Bon app'", 'Marseille', 'Client'),
 ('Bottom-Dollar Markets', 'Tsawassen', 'Client'),
 ('Bólido Comidas preparadas', 'Madrid', 'Client'),
 ('Cactus Comidas para llevar', 'Buenos Aires', 'Client'),
 ('Centro comercial Moctezuma', 'México D.F.', 'Client'),
 ('Chop-suey Chinese', 'Bern', 'Client'),
 ('Comércio Mineiro', 'São Paulo', 'Client'),
 ('Consolidated Holdings', 'London', 'Client'),
 ("Cooperativa de Quesos 'Las Cabras'", 'Oviedo', 'Fournisseur'),
 ('Die Wandernde Kuh', 'Stuttgart', 'Client'),
 ('Drachenblut Delikatessen', 'Aachen', 'Client'),
 ('Du monde entier', 'Nantes', 'Client'),
 ('Eastern Connection', 'London', 'Client'),
 ('Ernst Handel', 'Graz', 'Client'),
 ('Escargots Nouveaux', 'Montceau', 'Fournisseur'),
 ('Exotic Liquids', 'London', 'Fournisseur'),
 ('FISSA Fabrica Inter. Salchichas S.A.', 'Madrid', 'Client'),
 ('Familia Arquibaldo', 'São Paulo', 'Client'),
 ('Folies gourmandes', 'Lille', 'Client'),
 ('Folk och fä HB', 'Bräcke', 'Client'),
 ('Formaggi Fortini s.r.l.', 'Ravenna', 'Fournisseur'),
 ("Forêts d'érables", 'Ste-Hyacinthe', 'Fournisseur'),
 ('France restauration', 'Nantes', 'Client'),
 ('Franchi S.p.A.', 'Torino', 'Client'),
 ('Frankenversand', 'München', 'Client'),
 ('Furia Bacalhau e Frutos do Mar', 'Lisboa', 'Client'),
 ("G'day, Mate", 'Sydney', 'Fournisseur'),
 ('GROSELLA-Restaurante', 'Caracas', 'Client'),
 ('Gai pâturage', 'Annecy', 'Fournisseur'),
 ('Galería del gastrónomo', 'Barcelona', 'Client'),
 ('Godos Cocina Típica', 'Sevilla', 'Client'),
 ('Gourmet Lanchonetes', 'Campinas', 'Client'),
 ("Grandma Kelly's Homestead", 'Ann Arbor', 'Fournisseur'),
 ('Great Lakes Food Market', 'Eugene', 'Client'),
 ('HILARIÓN-Abastos', 'San Cristóbal', 'Client'),
 ('Hanari Carnes', 'Rio de Janeiro', 'Client'),
 ('Heli Süßwaren GmbH  Co. KG', 'Berlin', 'Fournisseur'),
 ('Hungry Coyote Import Store', 'Elgin', 'Client'),
 ('Hungry Owl All-Night Grocers', 'Cork', 'Client'),
 ('Island Trading', 'Cowes', 'Client'),
 ('Karkki Oy', 'Lappeenranta', 'Fournisseur'),
 ('Kelly', 'Ann Arbor', 'Fournisseur'),
 ('Königlich Essen', 'Brandenburg', 'Client'),
 ('LILA-Supermercado', 'Barquisimeto', 'Client'),
 ('LINO-Delicateses', 'I. de Margarita', 'Client'),
 ("La corne d'abondance", 'Versailles', 'Client'),
 ("La maison d'Asie", 'Toulouse', 'Client'),
 ('Laughing Bacchus Wine Cellars', 'Vancouver', 'Client'),
 ('Lazy K Kountry Store', 'Walla Walla', 'Client'),
 ('Lehmanns Marktstand', 'Frankfurt a.M.', 'Client'),
 ('Leka Trading', 'Singapore', 'Fournisseur'),
 ("Let's Stop N Shop", 'San Francisco', 'Client'),
 ('Lonesome Pine Restaurant', 'Portland', 'Client'),
 ('Lyngbysild', 'Lyngby', 'Fournisseur'),
 ('Ma Maison', 'Montréal', 'Fournisseur'),
 ('Magazzini Alimentari Riuniti', 'Bergamo', 'Client'),
 ('Maison Dewey', 'Bruxelles', 'Client'),
 ("Mayumi's", 'Osaka', 'Fournisseur'),
 ('Morgenstern Gesundkost', 'Leipzig', 'Client'),
 ('Mère Paillarde', 'Montréal', 'Client'),
 ('New England Seafood Cannery', 'Boston', 'Fournisseur'),
 ('Nord-Ost-Fisch Handelsgesellschaft mbH', 'Cuxhaven', 'Fournisseur'),
 ('Norske Meierier', 'Sandvika', 'Fournisseur'),
 ('North/South', 'London', 'Client'),
 ('Nouvelle-Orléans Cajun Delights', 'Nouvelle-Orléans', 'Fournisseur'),
 ('Océano Atlántico Ltda.', 'Buenos Aires', 'Client'),
 ('Old World Delicatessen', 'Anchorage', 'Client'),
 ('Ottilies Käseladen', 'Köln', 'Client'),
 ('PB Knäckebröd AB', 'Göteborg', 'Fournisseur'),
 ('Paris spécialités', 'Paris', 'Client'),
 ('Pasta Buttini s.r.l.', 'Salerno', 'Fournisseur'),
 ('Pavlova, Ltd.', 'Melbourne', 'Fournisseur'),
 ('Pericles Comidas clásicas', 'México D.F.', 'Client'),
 ('Piccolo und mehr', 'Salzburg', 'Client'),
 ('Plutzer Lebensmittelgroßmärkte AG', 'Frankfurt a.M.', 'Fournisseur'),
 ('Princesa Isabel Vinhos', 'Lisboa', 'Client'),
 ('QUICK-Stop', 'Cunewalde', 'Client'),
 ('Que Delícia', 'Rio de Janeiro', 'Client'),
 ('Queen Cozinha', 'São Paulo', 'Client'),
 ('Rancho grande', 'Buenos Aires', 'Client'),
 ('Rattlesnake Canyon Grocery', 'Albuquerque', 'Client'),
 ('Refrescos Americanas LTDA', 'São Paulo', 'Fournisseur'),
 ('Reggiani Caseifici', 'Reggio Emilia', 'Client'),
 ('Ricardo Adocicados', 'Rio de Janeiro', 'Client'),
 ('Richter Supermarkt', 'Genève', 'Client'),
 ('Romero y tomillo', 'Madrid', 'Client'),
 ('Santé Gourmet', 'Stavern', 'Client'),
 ('Save-a-lot Markets', 'Boise', 'Client'),
 ('Seven Seas Imports', 'London', 'Client'),
 ('Simons bistro', 'København', 'Client'),
 ('Specialty Biscuits, Ltd.', 'Manchester', 'Fournisseur'),
 ('Split Rail Beer  Ale', 'Lander', 'Client'),
 ('Spécialités du monde', 'Paris', 'Client'),
 ('Suprêmes délices', 'Charleroi', 'Client'),
 ('Svensk Sjöföda AB', 'Stockholm', 'Fournisseur'),
 ('The Big Cheese', 'Portland', 'Client'),
 ('The Cracker Box', 'Butte', 'Client'),
 ('Tokyo Traders', 'Tokyo', 'Fournisseur'),
 ('Toms Spezialitäten', 'Münster', 'Client'),
 ('Tortuga Restaurante', 'México D.F.', 'Client'),
 ('Tradição Hipermercados', 'São Paulo', 'Client'),
 ("Trail's Head Gourmet Provisioners", 'Kirkland', 'Client'),
 ('Vaffeljernet', 'Århus', 'Client'),
 ('Victuailles en stock', 'Lyon', 'Client'),
 ('Vins et alcools Chevalier', 'Reims', 'Client'),
 ('Wartian Herkku', 'Oulu', 'Client'),
 ('Wellington Importadora', 'Resende', 'Client'),
 ('White Clover Markets', 'Seattle', 'Client'),
 ('Wilman Kala', 'Helsinki', 'Client'),
 ('Wolski  Zajazd', 'Warszawa', 'Client'),
 ('Zaanse Snoepfabriek', 'Zaandam', 'Fournisseur')]

# L’opérateur INTERSECT

<img src="https://raw.githubusercontent.com/rbizoi/IntelligenceEnDonneesDeSante/main/InterrogationSQL/images/intersect.png" width="400">

In [5]:
%%sql 
SELECT VILLE,                                        
       NOM_PRODUIT                                   
FROM CLIENTS CL                                      
     JOIN COMMANDES CO                               
        ON ( CL.CODE_CLIENT = CO.CODE_CLIENT)        
     JOIN DETAILS_COMMANDES DC                       
        ON ( CO.NO_COMMANDE = DC.NO_COMMANDE)        
     JOIN PRODUITS PR                                
        ON ( DC.REF_PRODUIT = PR.REF_PRODUIT)        
INTERSECT                                            
SELECT VILLE, NOM_PRODUIT                            
FROM PRODUITS PR                                     
     JOIN FOURNISSEURS FR                            
        ON ( PR.NO_FOURNISSEUR = FR.NO_FOURNISSEUR )

 * oracle+cx_oracle://stagiaire:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Berlin', 'Granola'),
 ('Berlin', 'Gumbär Gummibärchen'),
 ('Berlin', 'NuNuCa Nuß-Nougat-Creme'),
 ('Berlin', 'Schoggi Schokolade'),
 ('Frankfurt a.M.', 'Original Frankfurter grüne Soße'),
 ('Frankfurt a.M.', 'Rhönbräu Klosterbier'),
 ('Frankfurt a.M.', 'Rössle Sauerkraut'),
 ('Frankfurt a.M.', 'Thüringer Rostbratwurst'),
 ('Frankfurt a.M.', 'Wimmers gute Semmelknödel'),
 ('London', 'Aniseed Syrup'),
 ('London', 'Chai'),
 ('London', 'Chang'),
 ('Montréal', 'Pears'),
 ('Montréal', 'Pâté chinois'),
 ('Montréal', 'Tourtière'),
 ('Paris', 'Beer'),
 ('Paris', 'Chartreuse verte'),
 ('Paris', 'Côte de Blaye'),
 ('Paris', 'Hot Cereal'),
 ('Paris', 'Mozzarella'),
 ('São Paulo', 'Guaraná Fantástica')]

# L’opérateur DIFFERENCE

<img src="https://raw.githubusercontent.com/rbizoi/IntelligenceEnDonneesDeSante/main/InterrogationSQL/images/difference.png" width="400">

In [6]:
%%sql 
SELECT CO.NO_COMMANDE,                          
       CO.DATE_COMMANDE                         
FROM CLIENTS CL                                 
     JOIN COMMANDES CO                          
        ON ( CL.CODE_CLIENT = CO.CODE_CLIENT)   
     JOIN DETAILS_COMMANDES DC                  
        ON ( CO.NO_COMMANDE = DC.NO_COMMANDE)   
     JOIN PRODUITS PR                           
        ON ( DC.REF_PRODUIT = PR.REF_PRODUIT)   
WHERE PR.CODE_CATEGORIE = 1                     
MINUS                                           
SELECT CO.NO_COMMANDE,                          
    CO.DATE_COMMANDE                            
FROM CLIENTS CL                                 
     JOIN COMMANDES CO                          
        ON ( CL.CODE_CLIENT = CO.CODE_CLIENT)   
     JOIN DETAILS_COMMANDES DC                  
        ON ( CO.NO_COMMANDE = DC.NO_COMMANDE)   
     JOIN PRODUITS PR                           
        ON ( DC.REF_PRODUIT = PR.REF_PRODUIT)   
WHERE PR.CODE_CATEGORIE = 9

 * oracle+cx_oracle://stagiaire:***@51.91.76.248:15440/coursdb
0 rows affected.

[(215025, datetime.datetime(2010, 1, 3, 0, 0)),
 (215130, datetime.datetime(2010, 1, 9, 0, 0)),
 (215220, datetime.datetime(2010, 1, 13, 0, 0)),
 (215226, datetime.datetime(2010, 1, 13, 0, 0)),
 (215230, datetime.datetime(2010, 1, 13, 0, 0)),
 (215436, datetime.datetime(2010, 1, 22, 0, 0)),
 (215441, datetime.datetime(2010, 1, 22, 0, 0)),
 (215444, datetime.datetime(2010, 1, 22, 0, 0)),
 (215472, datetime.datetime(2010, 1, 24, 0, 0)),
 (215483, datetime.datetime(2010, 1, 24, 0, 0)),
 (215496, datetime.datetime(2010, 1, 25, 0, 0)),
 (215505, datetime.datetime(2010, 1, 26, 0, 0)),
 (215508, datetime.datetime(2010, 1, 26, 0, 0)),
 (215513, datetime.datetime(2010, 1, 26, 0, 0)),
 (215536, datetime.datetime(2010, 1, 27, 0, 0)),
 (215589, datetime.datetime(2010, 1, 30, 0, 0)),
 (215591, datetime.datetime(2010, 1, 30, 0, 0)),
 (215598, datetime.datetime(2010, 1, 30, 0, 0)),
 (215603, datetime.datetime(2010, 1, 30, 0, 0)),
 (215604, datetime.datetime(2010, 1, 30, 0, 0)),
 (215624, datetime.datetime(2010, 1, 31, 0, 0)),
 (215876, datetime.datetime(2010, 2, 12, 0, 0)),
 (215884, datetime.datetime(2010, 2, 12, 0, 0)),
 (215888, datetime.datetime(2010, 2, 12, 0, 0)),
 (215894, datetime.datetime(2010, 2, 12, 0, 0)),
 (215904, datetime.datetime(2010, 2, 13, 0, 0)),
 (215982, datetime.datetime(2010, 2, 17, 0, 0)),
 (216029, datetime.datetime(2010, 2, 19, 0, 0)),
 (216033, datetime.datetime(2010, 2, 19, 0, 0)),
 (216043, datetime.datetime(2010, 2, 19, 0, 0)),
 (216091, datetime.datetime(2010, 2, 22, 0, 0)),
 (216092, datetime.datetime(2010, 2, 22, 0, 0)),
 (216093, datetime.datetime(2010, 2, 22, 0, 0)),
 (216095, datetime.datetime(2010, 2, 22, 0, 0)),
 (216096, datetime.datetime(2010, 2, 22, 0, 0)),
 (216098, datetime.datetime(2010, 2, 22, 0, 0)),
 (216102, datetime.datetime(2010, 2, 22, 0, 0)),
 (216103, datetime.datetime(2010, 2, 22, 0, 0)),
 (216121, datetime.datetime(2010, 2, 23, 0, 0)),
 (216129, datetime.datetime(2010, 2, 23, 0, 0)),
 (216131, datetime.datetime(2010, 2, 23, 0, 0)),
 (216140, datetime.datetime(2010, 2, 23, 0, 0)),
 (216142, datetime.datetime(2010, 2, 23, 0, 0)),
 (216205, datetime.datetime(2010, 2, 26, 0, 0)),
 (216209, datetime.datetime(2010, 2, 26, 0, 0)),
 (216212, datetime.datetime(2010, 2, 26, 0, 0)),
 (216214, datetime.datetime(2010, 2, 26, 0, 0)),
 (216242, datetime.datetime(2010, 2, 28, 0, 0)),
 (216333, datetime.datetime(2010, 3, 5, 0, 0)),
 (216334, datetime.datetime(2010, 3, 5, 0, 0)),
 (216336, datetime.datetime(2010, 3, 5, 0, 0)),
 (216338, datetime.datetime(2010, 3, 5, 0, 0)),
 (216355, datetime.datetime(2010, 3, 6, 0, 0)),
 (216358, datetime.datetime(2010, 3, 6, 0, 0)),
 (216365, datetime.datetime(2010, 3, 6, 0, 0)),
 (216368, datetime.datetime(2010, 3, 6, 0, 0)),
 (216430, datetime.datetime(2010, 3, 10, 0, 0)),
 (216439, datetime.datetime(2010, 3, 10, 0, 0)),
 (216448, datetime.datetime(2010, 3, 10, 0, 0)),
 (216449, datetime.datetime(2010, 3, 10, 0, 0)),
 (216453, datetime.datetime(2010, 3, 11, 0, 0)),
 (216464, datetime.datetime(2010, 3, 11, 0, 0)),
 (216472, datetime.datetime(2010, 3, 11, 0, 0)),
 (216516, datetime.datetime(2010, 3, 14, 0, 0)),
 (216518, datetime.datetime(2010, 3, 14, 0, 0)),
 (216534, datetime.datetime(2010, 3, 14, 0, 0)),
 (216581, datetime.datetime(2010, 3, 17, 0, 0)),
 (216585, datetime.datetime(2010, 3, 17, 0, 0)),
 (216587, datetime.datetime(2010, 3, 17, 0, 0)),
 (216592, datetime.datetime(2010, 3, 17, 0, 0)),
 (216594, datetime.datetime(2010, 3, 17, 0, 0)),
 (216602, datetime.datetime(2010, 3, 17, 0, 0)),
 (216608, datetime.datetime(2010, 3, 18, 0, 0)),
 (216610, datetime.datetime(2010, 3, 18, 0, 0)),
 (216614, datetime.datetime(2010, 3, 18, 0, 0)),
 (216628, datetime.datetime(2010, 3, 19, 0, 0)),
 (216648, datetime.datetime(2010, 3, 19, 0, 0)),
 (216650, datetime.datetime(2010, 3, 19, 0, 0)),
 (216659, datetime.datetime(2010, 3, 20, 0, 0)),
 (216664, datetime.datetime(2010, 3, 20, 0, 0)),
 (216668, datetime.datetime(2010, 3, 20, 0, 0)),
 (216670, datetime.datetime(2010, 3, 20, 0, 0)),
 (216740, datetime.datetime(2010, 3, 23, 0, 0)),
 (216763, datetime.datetime(2010, 3, 24, 0, 0)),
 (216765, datetime.datetime(2010, 3, 24, 0, 0)),
 (216772, datetime.datetime(2010, 3, 24, 0, 0)),
 (216916, datetime.datetime(2010, 3, 31, 0, 0)),
 (216921, datetime.datetime(2010, 3, 31, 0, 0)),
 (217045, datetime.datetime(2010, 4, 6, 0, 0)),
 (217047, datetime.datetime(2010, 4, 7, 0, 0)),
 (217061, datetime.datetime(2010, 4, 7, 0, 0)),
 (217062, datetime.datetime(2010, 4, 7, 0, 0)),
 (217188, datetime.datetime(2010, 4, 14, 0, 0)),
 (217192, datetime.datetime(2010, 4, 14, 0, 0)),
 (217200, datetime.datetime(2010, 4, 14, 0, 0)),
 (217203, datetime.datetime(2010, 4, 14, 0, 0)),
 (217241, datetime.datetime(2010, 4, 16, 0, 0)),
 (217244, datetime.datetime(2010, 4, 16, 0, 0)),
 (217250, datetime.datetime(2010, 4, 16, 0, 0)),
 (217296, datetime.datetime(2010, 4, 18, 0, 0)),
 (217349, datetime.datetime(2010, 4, 20, 0, 0)),
 (217357, datetime.datetime(2010, 4, 20, 0, 0)),
 (217377, datetime.datetime(2010, 4, 21, 0, 0)),
 (217383, datetime.datetime(2010, 4, 21, 0, 0)),
 (217396, datetime.datetime(2010, 4, 22, 0, 0)),
 (217478, datetime.datetime(2010, 4, 26, 0, 0)),
 (217504, datetime.datetime(2010, 4, 28, 0, 0)),
 (217505, datetime.datetime(2010, 4, 28, 0, 0)),
 (217507, datetime.datetime(2010, 4, 28, 0, 0)),
 (217516, datetime.datetime(2010, 4, 28, 0, 0)),
 (217520, datetime.datetime(2010, 4, 29, 0, 0)),
 (217524, datetime.datetime(2010, 4, 29, 0, 0)),
 (217527, datetime.datetime(2010, 4, 29, 0, 0)),
 (217533, datetime.datetime(2010, 4, 29, 0, 0)),
 (217609, datetime.datetime(2010, 5, 4, 0, 0)),
 (217624, datetime.datetime(2010, 5, 4, 0, 0)),
 (217688, datetime.datetime(2010, 5, 8, 0, 0)),
 (217694, datetime.datetime(2010, 5, 8, 0, 0)),
 (217698, datetime.datetime(2010, 5, 8, 0, 0)),
 (217708, datetime.datetime(2010, 5, 8, 0, 0)),
 (217845, datetime.datetime(2010, 5, 15, 0, 0)),
 (217860, datetime.datetime(2010, 5, 15, 0, 0)),
 (217876, datetime.datetime(2010, 5, 16, 0, 0)),
 (217899, datetime.datetime(2010, 5, 17, 0, 0)),
 (217907, datetime.datetime(2010, 5, 17, 0, 0)),
 (217908, datetime.datetime(2010, 5, 17, 0, 0)),
 (217912, datetime.datetime(2010, 5, 18, 0, 0)),
 (217917, datetime.datetime(2010, 5, 18, 0, 0)),
 (217919, datetime.datetime(2010, 5, 18, 0, 0)),
 (217924, datetime.datetime(2010, 5, 18, 0, 0)),
 (217936, datetime.datetime(2010, 5, 18, 0, 0)),
 (217945, datetime.datetime(2010, 5, 19, 0, 0)),
 (217956, datetime.datetime(2010, 5, 19, 0, 0)),
 (217961, datetime.datetime(2010, 5, 19, 0, 0)),
 (217964, datetime.datetime(2010, 5, 19, 0, 0)),
 (217967, datetime.datetime(2010, 5, 20, 0, 0)),
 (217970, datetime.datetime(2010, 5, 20, 0, 0)),
 (217975, datetime.datetime(2010, 5, 20, 0, 0)),
 (217976, datetime.datetime(2010, 5, 20, 0, 0)),
 (217985, datetime.datetime(2010, 5, 20, 0, 0)),
 (217986, datetime.datetime(2010, 5, 20, 0, 0)),
 (218010, datetime.datetime(2010, 5, 22, 0, 0)),
 (218014, datetime.datetime(2010, 5, 22, 0, 0)),
 (218025, datetime.datetime(2010, 5, 22, 0, 0)),
 (218051, datetime.datetime(2010, 5, 23, 0, 0)),
 (218054, datetime.datetime(2010, 5, 23, 0, 0)),
 (218110, datetime.datetime(2010, 5, 26, 0, 0)),
 (218113, datetime.datetime(2010, 5, 26, 0, 0)),
 (218115, datetime.datetime(2010, 5, 26, 0, 0)),
 (218125, datetime.datetime(2010, 5, 26, 0, 0)),
 (218129, datetime.datetime(2010, 5, 26, 0, 0)),
 (218160, datetime.datetime(2010, 5, 28, 0, 0)),
 (218165, datetime.datetime(2010, 5, 28, 0, 0)),
 (218284, datetime.datetime(2010, 6, 3, 0, 0)),
 (218285, datetime.datetime(2010, 6, 3, 0, 0)),
 (218291, datetime.datetime(2010, 6, 3, 0, 0)),
 (218311, datetime.datetime(2010, 6, 4, 0, 0)),
 (218324, datetime.datetime(2010, 6, 4, 0, 0)),
 (218435, datetime.datetime(2010, 6, 9, 0, 0)),
 (218439, datetime.datetime(2010, 6, 9, 0, 0)),
 (218443, datetime.datetime(2010, 6, 9, 0, 0)),
 (218446, datetime.datetime(2010, 6, 9, 0, 0)),
 (218449, datetime.datetime(2010, 6, 9, 0, 0)),
 (218495, datetime.datetime(2010, 6, 12, 0, 0)),
 (218497, datetime.datetime(2010, 6, 12, 0, 0)),
 (218503, datetime.datetime(2010, 6, 12, 0, 0)),
 (218504, datetime.datetime(2010, 6, 12, 0, 0)),
 (218592, datetime.datetime(2010, 6, 17, 0, 0)),
 (218611, datetime.datetime(2010, 6, 17, 0, 0)),
 (218621, datetime.datetime(2010, 6, 18, 0, 0)),
 (218627, datetime.datetime(2010, 6, 18, 0, 0)),
 (218787, datetime.datetime(2010, 6, 25, 0, 0)),
 (218838, datetime.datetime(2010, 6, 28, 0, 0)),
 (218840, datetime.datetime(2010, 6, 28, 0, 0)),
 (218848, datetime.datetime(2010, 6, 28, 0, 0)),
 (218850, datetime.datetime(2010, 6, 28, 0, 0)),
 (218851, datetime.datetime(2010, 6, 28, 0, 0)),
 (218855, datetime.datetime(2010, 6, 28, 0, 0)),
 (218941, datetime.datetime(2010, 7, 4, 0, 0)),
 (218944, datetime.datetime(2010, 7, 4, 0, 0)),
 (218960, datetime.datetime(2010, 7, 5, 0, 0)),
 (218967, datetime.datetime(2010, 7, 5, 0, 0)),
 (219062, datetime.datetime(2010, 7, 10, 0, 0)),
 (219067, datetime.datetime(2010, 7, 10, 0, 0)),
 (219070, datetime.datetime(2010, 7, 10, 0, 0)),
 (219073, datetime.datetime(2010, 7, 11, 0, 0)),
 (219078, datetime.datetime(2010, 7, 11, 0, 0)),
 (219164, datetime.datetime(2010, 7, 14, 0, 0)),
 (219168, datetime.datetime(2010, 7, 14, 0, 0)),
 (219171, datetime.datetime(2010, 7, 14, 0, 0)),
 (219174, datetime.datetime(2010, 7, 15, 0, 0)),
 (219176, datetime.datetime(2010, 7, 15, 0, 0)),
 (219178, datetime.datetime(2010, 7, 15, 0, 0)),
 (219179, datetime.datetime(2010, 7, 15, 0, 0)),
 (219182, datetime.datetime(2010, 7, 15, 0, 0)),
 (219188, datetime.datetime(2010, 7, 15, 0, 0)),
 (219194, datetime.datetime(2010, 7, 15, 0, 0)),
 (219207, datetime.datetime(2010, 7, 16, 0, 0)),
 (219219, datetime.datetime(2010, 7, 16, 0, 0)),
 (219260, datetime.datetime(2010, 7, 18, 0, 0)),
 (219264, datetime.datetime(2010, 7, 18, 0, 0)),
 (219269, datetime.datetime(2010, 7, 18, 0, 0)),
 (219320, datetime.datetime(2010, 7, 21, 0, 0)),
 (219330, datetime.datetime(2010, 7, 22, 0, 0)),
 (219337, datetime.datetime(2010, 7, 22, 0, 0)),
 (219346, datetime.datetime(2010, 7, 23, 0, 0)),
 (219347, datetime.datetime(2010, 7, 23, 0, 0)),
 (219359, datetime.datetime(2010, 7, 23, 0, 0)),
 (219377, datetime.datetime(2010, 7, 24, 0, 0)),
 (219415, datetime.datetime(2010, 7, 26, 0, 0)),
 (219427, datetime.datetime(2010, 7, 26, 0, 0)),
 (219433, datetime.datetime(2010, 7, 26, 0, 0)),
 (219436, datetime.datetime(2010, 7, 26, 0, 0)),
 (219519, datetime.datetime(2010, 7, 30, 0, 0)),
 (219525, datetime.datetime(2010, 7, 30, 0, 0)),
 (219527, datetime.datetime(2010, 7, 30, 0, 0)),
 (219539, datetime.datetime(2010, 7, 31, 0, 0)),
 (219540, datetime.datetime(2010, 7, 31, 0, 0)),
 (219546, datetime.datetime(2010, 7, 31, 0, 0)),
 (219623, datetime.datetime(2010, 8, 4, 0, 0)),
 (219746, datetime.datetime(2010, 8, 9, 0, 0)),
 (219847, datetime.datetime(2010, 8, 14, 0, 0)),
 (219848, datetime.datetime(2010, 8, 14, 0, 0)),
 (219850, datetime.datetime(2010, 8, 14, 0, 0)),
 (219854, datetime.datetime(2010, 8, 14, 0, 0)),
 (219855, datetime.datetime(2010, 8, 14, 0, 0)),
 (219886, datetime.datetime(2010, 8, 16, 0, 0)),
 (219889, datetime.datetime(2010, 8, 16, 0, 0)),
 (219910, datetime.datetime(2010, 8, 18, 0, 0)),
 (219915, datetime.datetime(2010, 8, 18, 0, 0)),
 (219928, datetime.datetime(2010, 8, 18, 0, 0)),
 (219933, datetime.datetime(2010, 8, 19, 0, 0)),
 (219943, datetime.datetime(2010, 8, 19, 0, 0)),
 (220055, datetime.datetime(2010, 8, 24, 0, 0)),
 (220057, datetime.datetime(2010, 8, 24, 0, 0)),
 (220061, datetime.datetime(2010, 8, 24, 0, 0)),
 (220067, datetime.datetime(2010, 8, 24, 0, 0)),
 (220068, datetime.datetime(2010, 8, 24, 0, 0)),
 (220070, datetime.datetime(2010, 8, 24, 0, 0)),
 (220071, datetime.datetime(2010, 8, 24, 0, 0)),
 (220073, datetime.datetime(2010, 8, 24, 0, 0)),
 (220080, datetime.datetime(2010, 8, 24, 0, 0)),
 (220088, datetime.datetime(2010, 8, 25, 0, 0)),
 (220118, datetime.datetime(2010, 8, 26, 0, 0)),
 (220121, datetime.datetime(2010, 8, 26, 0, 0)),
 (220126, datetime.datetime(2010, 8, 26, 0, 0)),
 (220132, datetime.datetime(2010, 8, 26, 0, 0)),
 (220134, datetime.datetime(2010, 8, 26, 0, 0)),
 (220136, datetime.datetime(2010, 8, 26, 0, 0)),
 (220140, datetime.datetime(2010, 8, 26, 0, 0)),
 (220165, datetime.datetime(2010, 8, 28, 0, 0)),
 (220167, datetime.datetime(2010, 8, 28, 0, 0)),
 (220178, datetime.datetime(2010, 8, 28, 0, 0)),
 (220181, datetime.datetime(2010, 8, 28, 0, 0)),
 (220185, datetime.datetime(2010, 8, 28, 0, 0)),
 (220374, datetime.datetime(2010, 9, 7, 0, 0)),
 (220484, datetime.datetime(2010, 9, 12, 0, 0)),
 (220513, datetime.datetime(2010, 9, 14, 0, 0)),
 (220514, datetime.datetime(2010, 9, 14, 0, 0)),
 (220523, datetime.datetime(2010, 9, 14, 0, 0)),
 (220530, datetime.datetime(2010, 9, 15, 0, 0)),
 (220542, datetime.datetime(2010, 9, 15, 0, 0)),
 (220543, datetime.datetime(2010, 9, 15, 0, 0)),
 (220563, datetime.datetime(2010, 9, 17, 0, 0)),
 (220565, datetime.datetime(2010, 9, 17, 0, 0)),
 (220572, datetime.datetime(2010, 9, 17, 0, 0)),
 (220574, datetime.datetime(2010, 9, 17, 0, 0)),
 (220587, datetime.datetime(2010, 9, 18, 0, 0)),
 (220598, datetime.datetime(2010, 9, 18, 0, 0)),
 (220768, datetime.datetime(2010, 9, 26, 0, 0)),
 (220771, datetime.datetime(2010, 9, 26, 0, 0)),
 (220781, datetime.datetime(2010, 9, 26, 0, 0)),
 (220835, datetime.datetime(2010, 9, 28, 0, 0)),
 (220839, datetime.datetime(2010, 9, 29, 0, 0)),
 (220855, datetime.datetime(2010, 9, 29, 0, 0)),
 (220860, datetime.datetime(2010, 9, 29, 0, 0)),
 (220946, datetime.datetime(2010, 10, 2, 0, 0)),
 (220975, datetime.datetime(2010, 10, 4, 0, 0)),
 (220982, datetime.datetime(2010, 10, 4, 0, 0)),
 (220984, datetime.datetime(2010, 10, 4, 0, 0)),
 (220986, datetime.datetime(2010, 10, 4, 0, 0)),
 (220987, datetime.datetime(2010, 10, 4, 0, 0)),
 (220991, datetime.datetime(2010, 10, 4, 0, 0)),
 (221032, datetime.datetime(2010, 10, 6, 0, 0)),
 (221035, datetime.datetime(2010, 10, 6, 0, 0)),
 (221044, datetime.datetime(2010, 10, 7, 0, 0)),
 (221053, datetime.datetime(2010, 10, 7, 0, 0)),
 (221054, datetime.datetime(2010, 10, 7, 0, 0)),
 (221059, datetime.datetime(2010, 10, 7, 0, 0)),
 (221063, datetime.datetime(2010, 10, 8, 0, 0)),
 (221069, datetime.datetime(2010, 10, 8, 0, 0)),
 (221075, datetime.datetime(2010, 10, 8, 0, 0)),
 (221076, datetime.datetime(2010, 10, 8, 0, 0)),
 (221143, datetime.datetime(2010, 10, 11, 0, 0)),
 (221165, datetime.datetime(2010, 10, 12, 0, 0)),
 (221174, datetime.datetime(2010, 10, 12, 0, 0)),
 (221179, datetime.datetime(2010, 10, 12, 0, 0)),
 (221182, datetime.datetime(2010, 10, 12, 0, 0)),
 (221214, datetime.datetime(2010, 10, 14, 0, 0)),
 (221217, datetime.datetime(2010, 10, 14, 0, 0)),
 (221218, datetime.datetime(2010, 10, 14, 0, 0)),
 (221219, datetime.datetime(2010, 10, 14, 0, 0)),
 (221347, datetime.datetime(2010, 10, 19, 0, 0)),
 (221445, datetime.datetime(2010, 10, 23, 0, 0)),
 (221452, datetime.datetime(2010, 10, 23, 0, 0)),
 (221594, datetime.datetime(2010, 10, 30, 0, 0)),
 (221604, datetime.datetime(2010, 10, 30, 0, 0)),
 (221629, datetime.datetime(2010, 10, 31, 0, 0)),
 (221637, datetime.datetime(2010, 11, 1, 0, 0)),
 (221685, datetime.datetime(2010, 11, 3, 0, 0)),
 (221687, datetime.datetime(2010, 11, 3, 0, 0)),
 (221695, datetime.datetime(2010, 11, 3, 0, 0)),
 (221700, datetime.datetime(2010, 11, 3, 0, 0)),
 (221734, datetime.datetime(2010, 11, 5, 0, 0)),
 (221737, datetime.datetime(2010, 11, 5, 0, 0)),
 (221748, datetime.datetime(2010, 11, 5, 0, 0)),
 (221756, datetime.datetime(2010, 11, 5, 0, 0)),
 (221831, datetime.datetime(2010, 11, 9, 0, 0)),
 (221835, datetime.datetime(2010, 11, 9, 0, 0)),
 (221885, datetime.datetime(2010, 11, 12, 0, 0)),
 (221889, datetime.datetime(2010, 11, 12, 0, 0)),
 (221891, datetime.datetime(2010, 11, 12, 0, 0)),
 (221893, datetime.datetime(2010, 11, 12, 0, 0)),
 (221897, datetime.datetime(2010, 11, 12, 0, 0)),
 (221954, datetime.datetime(2010, 11, 14, 0, 0)),
 (222071, datetime.datetime(2010, 11, 20, 0, 0)),
 (222249, datetime.datetime(2010, 11, 28, 0, 0)),
 (222255, datetime.datetime(2010, 11, 28, 0, 0)),
 (222346, datetime.datetime(2010, 12, 3, 0, 0)),
 (222347, datetime.datetime(2010, 12, 3, 0, 0)),
 (222354, datetime.datetime(2010, 12, 3, 0, 0)),
 (222470, datetime.datetime(2010, 12, 8, 0, 0)),
 (222477, datetime.datetime(2010, 12, 9, 0, 0)),
 (222479, datetime.datetime(2010, 12, 9, 0, 0)),
 (222484, datetime.datetime(2010, 12, 9, 0, 0)),
 (222626, datetime.datetime(2010, 12, 16, 0, 0)),
 (222628, datetime.datetime(2010, 12, 16, 0, 0)),
 (222631, datetime.datetime(2010, 12, 16, 0, 0)),
 (222632, datetime.datetime(2010, 12, 16, 0, 0)),
 (222633, datetime.datetime(2010, 12, 16, 0, 0)),
 (222639, datetime.datetime(2010, 12, 16, 0, 0)),
 (222642, datetime.datetime(2010, 12, 16, 0, 0)),
 (222644, datetime.datetime(2010, 12, 16, 0, 0)),
 (222645, datetime.datetime(2010, 12, 16, 0, 0)),
 (222653, datetime.datetime(2010, 12, 17, 0, 0)),
 (222656, datetime.datetime(2010, 12, 17, 0, 0)),
 (222668, datetime.datetime(2010, 12, 17, 0, 0)),
 (222678, datetime.datetime(2010, 12, 18, 0, 0)),
 (222855, datetime.datetime(2010, 12, 27, 0, 0)),
 (222862, datetime.datetime(2010, 12, 27, 0, 0)),
 (222868, datetime.datetime(2010, 12, 27, 0, 0)),
 (222870, datetime.datetime(2010, 12, 27, 0, 0)),
 (222878, datetime.datetime(2010, 12, 28, 0, 0)),
 (222958, datetime.datetime(2011, 1, 1, 0, 0)),
 (222960, datetime.datetime(2011, 1, 1, 0, 0)),
 (222967, datetime.datetime(2011, 1, 1, 0, 0)),
 (223172, datetime.datetime(2011, 1, 10, 0, 0)),
 (223174, datetime.datetime(2011, 1, 10, 0, 0)),
 (223178, datetime.datetime(2011, 1, 10, 0, 0)),
 (223180, datetime.datetime(2011, 1, 10, 0, 0)),
 (223182, datetime.datetime(2011, 1, 10, 0, 0)),
 (223183, datetime.datetime(2011, 1, 10, 0, 0)),
 (223186, datetime.datetime(2011, 1, 10, 0, 0)),
 (223187, datetime.datetime(2011, 1, 10, 0, 0)),
 (223213, datetime.datetime(2011, 1, 11, 0, 0)),
 (223227, datetime.datetime(2011, 1, 12, 0, 0)),
 (223239, datetime.datetime(2011, 1, 12, 0, 0)),
 (223254, datetime.datetime(2011, 1, 12, 0, 0)),
 (223341, datetime.datetime(2011, 1, 16, 0, 0)),
 (223344, datetime.datetime(2011, 1, 16, 0, 0)),
 (223345, datetime.datetime(2011, 1, 16, 0, 0)),
 (223353, datetime.datetime(2011, 1, 16, 0, 0)),
 (223440, datetime.datetime(2011, 1, 19, 0, 0)),
 (223447, datetime.datetime(2011, 1, 19, 0, 0)),
 (223458, datetime.datetime(2011, 1, 20, 0, 0)),
 (223462, datetime.datetime(2011, 1, 20, 0, 0)),
 (223479, datetime.datetime(2011, 1, 20, 0, 0)),
 (223481, datetime.datetime(2011, 1, 20, 0, 0)),
 (223511, datetime.datetime(2011, 1, 22, 0, 0)),
 (223546, datetime.datetime(2011, 1, 23, 0, 0)),
 (223547, datetime.datetime(2011, 1, 23, 0, 0)),
 (223552, datetime.datetime(2011, 1, 23, 0, 0)),
 (223564, datetime.datetime(2011, 1, 23, 0, 0)),
 (223565, datetime.datetime(2011, 1, 23, 0, 0)),
 (223624, datetime.datetime(2011, 1, 26, 0, 0)),
 (223629, datetime.datetime(2011, 1, 26, 0, 0)),
 (223631, datetime.datetime(2011, 1, 26, 0, 0)),
 (223632, datetime.datetime(2011, 1, 26, 0, 0)),
 (223648, datetime.datetime(2011, 1, 26, 0, 0)),
 (223653, datetime.datetime(2011, 1, 26, 0, 0)),
 (223676, datetime.datetime(2011, 1, 27, 0, 0)),
 (223694, datetime.datetime(2011, 1, 28, 0, 0)),
 (223698, datetime.datetime(2011, 1, 28, 0, 0)),
 (223722, datetime.datetime(2011, 1, 28, 0, 0)),
 (223760, datetime.datetime(2011, 1, 30, 0, 0)),
 (223763, datetime.datetime(2011, 1, 30, 0, 0)),
 (223776, datetime.datetime(2011, 1, 30, 0, 0)),
 (223777, datetime.datetime(2011, 1, 30, 0, 0)),
 (223784, datetime.datetime(2011, 1, 30, 0, 0)),
 (223897, datetime.datetime(2011, 2, 3, 0, 0)),
 (223903, datetime.datetime(2011, 2, 3, 0, 0)),
 (223917, datetime.datetime(2011, 2, 3, 0, 0)),
 (223922, datetime.datetime(2011, 2, 3, 0, 0)),
 (223925, datetime.datetime(2011, 2, 3, 0, 0)),
 (224079, datetime.datetime(2011, 2, 10, 0, 0)),
 (224082, datetime.datetime(2011, 2, 10, 0, 0)),
 (224091, datetime.datetime(2011, 2, 10, 0, 0)),
 (224094, datetime.datetime(2011, 2, 10, 0, 0)),

# Sous-requête monolignes

<img src="https://raw.githubusercontent.com/rbizoi/IntelligenceEnDonneesDeSante/main/InterrogationSQL/images/sr01.png" width="400">

In [7]:
%%sql 
SELECT NOM_PRODUIT 
FROM PRODUITS 
WHERE UNITES_STOCK = (SELECT MAX(UNITES_STOCK) FROM PRODUITS)

 * oracle+cx_oracle://stagiaire:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Potato Chips',)]

In [8]:
%%sql 
SELECT CL.SOCIETE,                                     
       CO.NO_COMMANDE,                                 
       COUNT( DC.REF_PRODUIT)                          
FROM CLIENTS CL                                        
     JOIN COMMANDES CO                                 
        ON ( CL.CODE_CLIENT = CO.CODE_CLIENT)          
     JOIN DETAILS_COMMANDES DC                         
        ON ( CO.NO_COMMANDE = DC.NO_COMMANDE)          
GROUP BY CL.SOCIETE,                                   
         CO.NO_COMMANDE                                
HAVING COUNT( DC.REF_PRODUIT) >=                       
   ( SELECT COUNT( DC.REF_PRODUIT)                     
     FROM COMMANDES CO                                 
          JOIN DETAILS_COMMANDES DC                    
               ON ( CO.NO_COMMANDE = DC.NO_COMMANDE)   
     WHERE  CO.NO_COMMANDE = 224975)

 * oracle+cx_oracle://stagiaire:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Hungry Owl All-Night Grocers', 220267, 52),
 ('Rancho grande', 215629, 52),
 ('Berglunds snabbköp', 216798, 52),
 ('Blondel père et fils', 224968, 52),
 ('Furia Bacalhau e Frutos do Mar', 225524, 52),
 ('Rattlesnake Canyon Grocery', 228419, 52),
 ('LINO-Delicateses', 224963, 52),
 ('Du monde entier', 216814, 52),
 ('White Clover Markets', 220279, 52),
 ('Laughing Bacchus Wine Cellars', 224974, 52),
 ('Die Wandernde Kuh', 216810, 52),
 ('The Big Cheese', 224975, 52)]

# Sous-requête multilignes

<img src="https://raw.githubusercontent.com/rbizoi/IntelligenceEnDonneesDeSante/main/InterrogationSQL/images/sr02.png" width="400">

In [9]:
%%sql 
SELECT SOCIETE,                                                
       VILLE,                                                  
       PAYS                                                    
FROM CLIENTS                                                   
WHERE  CODE_CLIENT IN (                                        
               SELECT CO.CODE_CLIENT                           
               FROM COMMANDES CO                               
                    JOIN EMPLOYES EM                           
                         ON ( EM.NO_EMPLOYE = CO.NO_EMPLOYE)   
               WHERE EM.REND_COMPTE = 11)

 * oracle+cx_oracle://stagiaire:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Wolski  Zajazd', 'Warszawa', 'Pologne'),
 ('Chop-suey Chinese', 'Bern', 'Suisse'),
 ('Ernst Handel', 'Graz', 'Autriche'),
 ('Toms Spezialitäten', 'Münster', 'Allemagne'),
 ('Lehmanns Marktstand', 'Frankfurt a.M.', 'Allemagne'),
 ('Alfreds Futterkiste', 'Berlin', 'Allemagne'),
 ('Blauer See Delikatessen', 'Mannheim', 'Allemagne'),
 ('Königlich Essen', 'Brandenburg', 'Allemagne'),
 ('Richter Supermarkt', 'Genève', 'Suisse'),
 ('Ottilies Käseladen', 'Köln', 'Allemagne'),
 ('Morgenstern Gesundkost', 'Leipzig', 'Allemagne'),
 ('QUICK-Stop', 'Cunewalde', 'Allemagne'),
 ('Frankenversand', 'München', 'Allemagne'),
 ('Piccolo und mehr', 'Salzburg', 'Autriche'),
 ('Drachenblut Delikatessen', 'Aachen', 'Allemagne'),
 ('Die Wandernde Kuh', 'Stuttgart', 'Allemagne')]

# Sous-requête synchronisée

<img src="https://raw.githubusercontent.com/rbizoi/IntelligenceEnDonneesDeSante/main/InterrogationSQL/images/sr03.png" width="400">

In [10]:
%%sql 
SELECT 
    CODE_CATEGORIE "Cat",                           
    NOM_PRODUIT,                                    
    UNITES_STOCK  "Stock",                          
    PRIX_UNITAIRE "Prix"                            
FROM PRODUITS P1                                       
WHERE UNITES_STOCK >(                                  
         SELECT AVG(UNITES_STOCK)*2                    
         FROM PRODUITS P2                              
         WHERE P2.CODE_CATEGORIE = P1.CODE_CATEGORIE)

 * oracle+cx_oracle://stagiaire:***@51.91.76.248:15440/coursdb
0 rows affected.

[(2, "Grandma's Boysenberry Spread", 120, Decimal('125')),
 (4, 'Queso Manchego La Pastora', 86, Decimal('190')),
 (3, 'NuNuCa Nuß-Nougat-Creme', 76, Decimal('70')),
 (8, 'Boston Crab Meat', 123, Decimal('92')),
 (4, 'Raclette Courdavault', 79, Decimal('275')),
 (4, 'Geitost', 112, Decimal('13')),
 (3, 'Valkoinen suklaa', 65, Decimal('81')),
 (2, "Sirop d'érable", 113, Decimal('143')),
 (1, 'Rhönbräu Klosterbier', 125, Decimal('39')),
 (2, 'Syrup', 100, Decimal('7.5')),
 (9, 'Boysenberry Spread', 100, Decimal('18.75')),
 (1, 'Green Tea', 125, Decimal('2')),
 (7, 'Potato Chips', 200, Decimal('0.49'))]

# Atelier 8.2	Les jointures complexes
## Les sous-requêtes monolignes
Écrivez les requêtes vous permettant d’afficher :

>> * Les produits pour lesquels la quantité en stock est inférieure à la moyenne.
>> * Les sociétés clientes et les numéros des commandes qui ont un nombre égal ou supérieur de produits achetés que la commande numéro '216798'.


## Les sous-requêtes multilignes
Écrivez les requêtes vous permettant d’afficher :
>> * Les sociétés clientes et leurs commandes pour tous les produits livrés par un fournisseur qui habite Paris.
>> * Les sociétés clientes françaises qui ont commandé le produit ‘Chai’ mais également qui ont commandé plus de 39 produits le '01/05/2011'.

## Les sous-requêtes synchronisée
Écrivez les requêtes vous permettant d’afficher :
>> * Les clients pour lesquels les frais de ports par commande dépassent leur moyenne globale des frais de ports.
>> * Le produit, le fournisseur et les unités en stock pour les produits qui ont un stock inférieur à la moyenne des unités en stock pour les produits du même fournisseur.
>> * Les clients et ses commandes pour les clients qui payent un port supérieur à la moyenne des commandes pour la même année.
>> * Les employés avec leur salaire et le pourcentage correspondant par rapport au total de la masse salariale par fonction. Essayez d’utiliser une sous-requête dans la clause « FROM ».